apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-java-sumo-config
  namespace: temporal-observability
  labels:
    app.kubernetes.io/name: temporal-java-sumo-observability
    app.kubernetes.io/component: config
data:
  SERVICE_NAME: temporal-java-sumo-observability
  DEPLOYMENT_ENVIRONMENT: eks
  APP_LOG_LEVEL: INFO
  TEMPORAL_TARGET: replace-with-temporal-frontend:7233
  TEMPORAL_NAMESPACE: replace-with-temporal-namespace
  TEMPORAL_TASK_QUEUE: HELLO_TASK_QUEUE
