apiVersion: v1
kind: Namespace
metadata:
  name: temporal-observability
  labels:
    app.kubernetes.io/part-of: temporal-observability
  annotations:
    sumologic.com/sourceCategory: kubernetes/temporal/java/worker
